[tool.poetry]
name = "pythonscrimbapoetry"
version = "0.1.0"
description = ""
authors = ["lekha9989 <lekha.m9989@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

